### ISSUE TITLE
[Request] Wildcard DNS Support

### ISSUE THREAD

**Issue by VindicoRory** [rapiz1/rathole#139]
Would it be possible to add wildcard dns support? The project is amazing as it is but the ability to bind specific services to wildcard dns records while also passing the traffic to a specified port client side would be extremely useful.
Keep up the good work, this project is the best tunnelling ive found so far.

**Comment by rapiz1** [comment]
> the ability to bind specific services to wildcard dns records while also passing the traffic to a specified port client side 

I don't know what this is referring to. Can you give a concrete example for your use case?

**Comment by VindicoRory** [comment]
Say I have a service running on my machine that I want to access from the internet running on port 8080.
Instead of running this through rathole and going to example.com:8080 to access the service, could I instead go to service.example.com and have that redirect the traffic to port 8080 on the client, and have the service.example.com defined by a wildcard dns entry so it could be whatever I wanted without having to manually edit the dns records.
Sort of like this:
`External Computer -> service.example.com -> rathole server -> client -> localhost:8080`
Im not sure if this is out of the scope of the project or not, but it would be great to hear your thoughts!

**Comment by rapiz1** [comment]
I don't get what should be done on the rathole side. Just point `service.example.com` to the rathole server.

Let the rathole server listen at `0.0.0.0` and point subdomains to the host that the rathole server is running on.

The mapping between domains and IP addresses is handled by the DNS provider. If you want some domains pointing to some IP, you have to tell the nameserver. Nothing needs to be done on rathole. For the wildcard usage, you can set `*.example.com` pointing to the rathole server, in the DNS provider's panel.

So I guess you were not sure about `server.bind_addr`? Generally, you want to set it to `0.0.0.0:some_port`. In this way, it will accept any IPv4 incoming traffic.

**Comment by VindicoRory** [comment]
I must have missed something in the documentation then, is there way in the config to distinguish between subdomains and redirect to different ports accordingly?

Currently my setup has example.com:8080 tunnelling to one client and example.com:8081 tunnelling to a different client.
How would I setup the config to recognise subdomains and tunnel accordingly without having to enter the port in the domain?
E.G
client1.example.com -> client1 on 8080
client2.example.com -> client2 on 8080

I dont want to have to enter the port in the domain, just have different subdomains be associated with different ports.
Sorry if this is already a thing and im missing something! Thank you so much for replying about this.

**Comment by rapiz1** [comment]
> is there way in the config to distinguish between subdomains and redirect to different ports accordingly?

It can't be done in rathole *alone*. However, this is a typical usage [where the forwarding is based on the domain](https://github.com/rapiz1/rathole/blob/main/docs/out-of-scope.md) and one of the considered scenarios that rathole is designed.

It's possible to do by combining rathole and nginx, when you want to forward HTTP(s) traffic.

Unfortunately, for non-HTTP, it's *technically impossible* because there's no way to know which domain a TCP packet comes from, unless the content of the TCP packet carries the text of the domain itself, like what HTTP does.

For HTTP(s), Use nginx to route based on the domain. The setup looks like this:
```
visitor -> client1.example.com -> HostA(nginx) -> HostA(rathole server) -> HostB(rathole client1)
visitor -> client2.example.com -> HostA(nginx) -> HostA(rathole server) -> HostB(rathole client2)
```

To achieve this, rathole server on HostA looks like this
```toml
[server]
# ...
[server.services.client1]
# expose the port locally so only nginx can access it
bind_addr = "127.0.0.1:8080"
[server.services.client2]
bind_addr = "127.0.0.1:8081"
```

Then set up nginx on Host A to route traffic to `127.0.0.1:8080` or `127.0.0.1:8081` based on domains. Relevant snippets will look like this:
```
server {
  server_name client1.example.com;
  location / {
    proxy_pass http://127.0.0.1:8080;
  }
}
server {
  server_name client2.example.com;
  location / {
    proxy_pass http://127.0.0.1:8081;
  }
}
```
I'm not expanding too much about nginx here. You can google `nginx route based on domains` and there are lots of results.

For now, it may sound kind of tedious to run additional software to do domain-based forwarding. But in terms of maintainability, performance, and flexibility, it is worth the effort.

So the idea is to use rathole for the NAT part, and let nginx do other HTTP(s) specific things. For the long term, I plan to create a web control panel around rathole and integrate with nginx to deliver an all-in-one solution.

**Comment by VindicoRory** [comment]
Thank you so much for such a detailed response, its a very useful answer.  I had wondered if there would need to be an additional nginx layer for this functionality and it makes sense as to why its needed. Love the project and will be following it closely. Thanks again

**Comment by liusong1111** [comment]
Pingora was open sourced, things become easy and interesting.

Port is hard to remember than name, and http forwarding is so common, so combining a reverse proxy is convenient.
I will try to integrate rathole and pingora in a private project, but still hope rathole do that in its core.
Rathole is so amazing, thanks for your job.
