### ISSUE TITLE
Server fails to work when two same client connect at the same time

### ISSUE THREAD

**Issue by HollisMeynell** [rapiz1/rathole#174]
If there are two clients using same configuration to connect to the server at the same time, the server won't work as expect.

## Suggestion

Can we verify the connection from client? We can check if there were already a connected client using same configuration with the new one. If it exist, then we just refuse the new connection.

**Comment by rapiz1** [comment]
Current behavior is dropping the previous connection because it's more robust. There's effectively no reliable way to detect if the previous client is still alive. If we reject the new connection, in the case where the old connection is problematic and decives the server, we can't recover from the failure.


No way to do what you suggest. Best we can do is to warn the user if the continuously dropping pattern appears.



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 10, 2022 12:46 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [rapiz1/rathole] Server fails to work when two same client connect atthe same time (Issue #174)




 
If there are two clients using same configuration to connect to the server at the same time, the server won't work as expect.
 
Suggestion
 
Can we verify the connection from client? We can check if there were already a connected client using same configuration with the new one. If it exist, then we just refuse the new connection.
