### ISSUE TITLE
will you add proxy-protocol support?

### ISSUE THREAD

**Issue by lootoos** [rapiz1/rathole#176]
in order to be able to get normal IP addresses to the minecraft server.
in order for the server to be able to receive external IP addresses of players.

**Comment by rapiz1** [comment]
Not possible as we previously discussed. That's application specific

**Comment by lootoos** [comment]
what does it mean depends on the application?
why does nginx support proxy_protocol and you are not in a state to suddenly support it?

**Comment by rapiz1** [comment]
Because what nginx means is HTTP proxy header which is defined in HTTP protocol and means nothing for TCP/UDP.



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 11, 2022 20:09 PM
To: ***@***.***&gt;;
Cc: "Yujia ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [rapiz1/rathole] will you add proxy-protocol support? (Issue#176)




 
what does it mean depends on the application?
 why does nginx support proxy_protocol and you are not in a state to suddenly support it?

**Comment by lootoos** [comment]
what an ignoramus you are in this matter.
 nginx supports proxy_protocol for minecraft server java: https://imgbb.com/FnpFhPk 
That is, nginx procy_protocol on; compatible with minecraft server java - but what prevents you from introducing proxy_protocol support?

**Comment by rapiz1** [comment]
Go learn some basics about the network stack or write your own software. I've already told you what to look for in #175 

Use nginx along with rathole is possible. And it's designed with regard to that at the first place.

**Comment by lootoos** [comment]
that is, will rathole work fine with nginx? provided that proxy_protocol on is enabled in nginx;
