### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fearek** [rapiz1/rathole#181]
Domain based forwarding for HTTP

Introducing these kind of features into rathole itself ultimately reinvent a nginx. Use nginx to do this and set rathole as the upstream. This method achieves better performance as well as flexibility.

how do I set up nginx with rathole? I want to send HTTP data through rathole but with modified headers so I can get requesting user IP

**Comment by fernvenue** [comment]
Since discussions are not yet enabled, I assume it's reasonable to ask questions here.

So here's an example, if we have a http service on the client side at port 80:

```
[server.services.example]
type = "tcp"
bind_addr = "127.0.0.1:8081"
nodelay = false

[client.services.example]
type = "tcp"
local_addr = "localhost:80"
nodelay = false
```

Now, we can access to this client side http service on the server side at `127.0.0.1:8081`, and next we can use nginx on the server side to add this service to the http/https service of the server:

```
...

  location / {
    proxy_pass http://127.0.0.1:8081/;
    proxy_set_header Host $host;
    ...
  }

...
```

All done, that's quite simple, right? Read the nginx docs before open an issue, maybe next time :)

**Comment by rapiz1** [comment]
@fernvenue Thanks very much for the example! That's what I'm expecting people using rathole. BTW, discussion is now enabled.
