### ISSUE TITLE
DNS records of `local_ip` doesn't cached.

### ISSUE THREAD

**Issue by fernvenue** [rapiz1/rathole#183]
**Describe the bug**
Hi, I just found out that rathole sent a lot of DNS requests for `local_ip`, can't we use cache for it or maybe just send request when TTL expired or target machine doesn't respond only? If rathole already support to use cache for DNS, could you please tell me how can I use this feature?

And I discovered https://github.com/rapiz1/rathole/issues/151 this, and I'm pretty sure that this is not the same issue, this one about `local_ip` address, not server address.

**To Reproduce**
1. Make a connection using rathole;
2. And check the local DNS server log.

**Configuration**
Configuration used to reproduce the behavior:

```
[server]
bind_addr = "0.0.0.0:2333"
[server.services.example]
token = "1029384756"
bind_addr = "0.0.0.0:443"

[client]
remote_addr = "example.com:2333"
[client.services.example]
token = "1029384756"
local_addr = "example.com:443"
```

**Environment:**
 - OS: debian 11 bullseye
- `rathole --version` output: 

```
rathole 
Build Timestamp:     2022-08-11T12:56:34.066343926+00:00
Build Version:       0.4.3
Commit SHA:          Some("2e9e7374bc046ecda23ebd0aefeb45a560498585")
Commit Date:         Some("2022-08-11T12:51:56+00:00")
Commit Branch:       Some("detached HEAD")
cargo Target Triple: x86_64-unknown-linux-gnu
cargo Profile:       release
cargo Features:      base64,client,default,hot_reload,noise,notify,server,snowstorm,tls,tokio_native_tls
```

- CPU architecture: `x86_64`

**Comment by rapiz1** [comment]
local_ip cache is not feasible because we have no reliable way to detect ip change. Handle DNS ttl and so on should be done with a DNS server, not a client. Caching ip is generally dangerous for clients. If you care about the local_ip query you can set up a local DNS server and enable caching. Then the local lookup should be trivial.



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 28, 2022 12:49 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [rapiz1/rathole] DNS records of `local_ip` doesn't cached. (Issue#183)




 
Describe the bug
 Hi, I just found out that rathole sent a lot of DNS requests for local_ip, can't we use cache for it or maybe just send request when TTL expired or target machine doesn't respond only? If rathole already support to use cache for DNS, could you please tell me how can I use this feature?
 
And I discovered #151 this, and I'm pretty sure that this is not the same issue, this one about local_ip address, not server address.
 
To Reproduce
 Steps to reproduce the behavior:
  
Make a connection using rathole;
 
And check the local DNS server log.
  
Configuration
 Configuration used to reproduce the behavior:
 [server] bind_addr = "0.0.0.0:2333" [server.services.example] token = "1029384756" bind_addr = "0.0.0.0:443" [client] remote_addr = "example.com:2333" [client.services.example] token = "1029384756" local_addr = "example.com:443"  
Environment:
  
OS: debian 11 bullseye
 
rathole --version output:
  rathole  Build Timestamp:     2022-08-11T12:56:34.066343926+00:00 Build Version:       0.4.3 Commit SHA:          Some("2e9e7374bc046ecda23ebd0aefeb45a560498585") Commit Date:         Some("2022-08-11T12:51:56+00:00") Commit Branch:       Some("detached HEAD") cargo Target Triple: x86_64-unknown-linux-gnu cargo Profile:       release cargo Features:      base64,client,default,hot_reload,noise,notify,server,snowstorm,tls,tokio_native_tls   
CPU architecture: x86_64

**Comment by fernvenue** [comment]
Sounds reasonable, thanks for your reply, and I'm clearly understood your concern. Do you agree with that we should add this to the [out-of-scope](https://github.com/rapiz1/rathole/blob/main/docs/out-of-scope.md) list so that others won't repeat this issue?

**Comment by rapiz1** [comment]
Yes that can be added



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 28, 2022 13:12 PM
To: ***@***.***&gt;;
Cc: "Yujia ***@***.******@***.***&gt;;
Subject: Re: [rapiz1/rathole] DNS records of `local_ip` doesn't cached. (Issue#183)




 
Sounds reasonable, thanks for your reply, and I'm clearly understood your concern. Do you agree with that we should add this to the out-of-scope list so that others won't repeat this issue?
