### ISSUE TITLE
Cant run the docker image on my raspberry pi

### ISSUE THREAD

**Issue by m1212e** [rapiz1/rathole#196]
Since the raspi is running on ARM the docker image does not work.
As far as I know it is possible to [enable multi processor support ](https://dev.to/tidalmigrations/multi-cpu-architecture-container-images-how-to-build-and-push-them-on-docker-hub-or-any-other-registry-2981)for docker images?

Is it planned to add support? Or do I need to build my own image?

**Comment by rapiz1** [comment]
I didn't build a image for ARM. You can build on your own.
I don't have a plan but it's nice to have



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 20, 2022 10:02 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [rapiz1/rathole] Cant run the docker image on my raspberry pi (Issue#196)




 
Since the raspi is running on ARM the docker image does not work.
 As far as I know it is possible to enable multi processor support for docker images?
 
Is it planned to add support? Or do I need to build my own image?

**Comment by m1212e** [comment]
Ok thanks for the info

**Comment by nemanjam** [comment]
Feel free to pull my `arm64` image built from he current source code.

```bash
docker pull nemanjamitic/my-rathole-arm64:v1.0
```

https://hub.docker.com/repository/docker/nemanjamitic/my-rathole-arm64/tags
