### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by rapiz1** [rapiz1/rathole#63]
Someone requests it and it should be easy to create one, though it doesn't seem quite useful to me. These days people are get used to just typing `docker run`.

A `Dockerfile` can be created under the root of the project.

**Comment by xylonx** [comment]
It's nice to set a github workflow for building and pushing images automatically based on git tags. @rapiz1 can you set the github secrets and create a corresponding workflow?

**Comment by rapiz1** [comment]
🤔 Still thinking about whether or not to add this.

**Comment by clarkmcc** [comment]
Definitely add it. Providing a Dockerfile at the very least for a service that can be deployed to the cloud (the server, not the client) is pretty standard imo.

**Comment by rapiz1** [comment]
> Providing a Dockerfile at the very least for a service that can be deployed to the cloud (the server, not the client) is pretty standard imo.

Fair.

But `rathole` is a single binary that can be easily deployed and just run. Using docker to run it doesn't bring additional convenience, except facilitating some container management systems. Do you need the docker image for practical usage?

**Comment by clarkmcc** [comment]
Nowadays, I never run services by setting them up on an EC2 instance and putting nginx in front of them (that's not to say that everyone does this). Instead, I always drop the container in an orchestrator like Kubernetes, Nomad or AWS Fargate. Orchestrators like Kubernetes also handle a lot of other things such as making sure the container is alive, and they handle load balancing and routing inherently. Containers are great because they're lightweight, no installation is involved, they "just work" right out of the box, etc.

Just a broader observation: based on my reading of your .md files and your responses to the issues here, I can tell that you're trying to avoid scope-creep by keeping this project lightweight. I think this is a good thing, however a good open-source project strikes a balance between catering to their users needs and the projects needs. Keeping a feature such as a Dockerfile, or a TCP-replacement protocol such as QUIC (https://github.com/rapiz1/rathole/issues/65) out of the scope of this project _only_ because it adds an additional file is not a good enough reason in my opinion.

Anyways, great work so far on this! I'm looking forward to seeing where it goes from here.

**Comment by rapiz1** [comment]
> Keeping a feature such as a Dockerfile, or a TCP-replacement protocol such as QUIC (#65) out of the scope of this project only because it adds an additional file is not a good enough reason in my opinion.

I didn't say these things were out of scope :) Actually I'm trying to figure out whether a feature request is something people really need, instead of being "fancy", and just "good to have".

**Comment by orhun** [comment]
I think a lightweight Docker image can be built using `musl` + `scratch` e.g.

```Dockerfile
FROM ekidd/rust-musl-builder:latest as builder
WORKDIR /home/rust/src
COPY . .
RUN cargo build --profile minimal
RUN mkdir -p build-out/
RUN cp target/x86_64-unknown-linux-musl/minimal/rathole build-out/

FROM scratch
WORKDIR /app
COPY --from=builder /home/rust/src/build-out/rathole .
USER 1000:1000
ENTRYPOINT ["./rathole"]
```

This image is only 8.55mb on my computer when built and runs perfectly fine according to my smoke tests.

Let me know if this is needed and I'm happy to submit a PR 🙂

**Comment by xylonx** [comment]
> I think a lightweight Docker image can be built using `musl` + `scratch` e.g.
> 
> ```dockerfile
> FROM ekidd/rust-musl-builder:latest as builder
> WORKDIR /home/rust/src
> COPY . .
> RUN cargo build --profile minimal
> RUN mkdir -p build-out/
> RUN cp target/x86_64-unknown-linux-musl/minimal/rathole build-out/
> 
> FROM scratch
> WORKDIR /app
> COPY --from=builder /home/rust/src/build-out/rathole .
> USER 1000:1000
> ENTRYPOINT ["./rathole"]
> ```
> 
> This image is only 8.55mb on my computer when built and runs fine according to my smoke tests.
> 
> Let me know if this is needed and I'm happy to submit a PR 🙂

Your image is much smaller than mine. Using scratch is fantastic. I'll close my pr. Hope yours🙂

**Comment by orhun** [comment]
> @orhun Seems great! Can you open a PR?

Sure! Do you want 2 separate Dockerfile's for client and server? (like @xylonx did in #66)

Or you can pass the config file into container like this:

```sh
docker run -it --rm -v "$(pwd)/examples/minimal/server.toml:/app/config.toml" rathole_img --server /app/config.toml

docker run -it --rm -v "$(pwd)/examples/minimal/client.toml:/app/config.toml" rathole --client /app/config.toml
```

I think having the client/server functionality in only one image is pretty sweet 🍓 

What do you think?

**Comment by rapiz1** [comment]
> What do you think?

I think it should be put in one image :)

`server` and `client` makes little difference in size. And in this case, users probably don't care about the difference of the binary size in KiB. So I would also suggest use the `release` profile, instead of the `minimal` one, which is intent to be used when every bits matter.

**Comment by rapiz1** [comment]
`v0.3.2` has been released, with [a docker image](https://hub.docker.com/r/rapiz1/rathole) 🎉
